/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.heinvdende.versionreview.test.client.ui.components;

import com.heinvdende.versionreview.test.modules.repository.domain.ChangedCodeFile;
import java.awt.Graphics;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLayeredPane;
import javax.swing.JScrollPane;
import syntaxhighlight.SyntaxHighlighter;

/**
 *
 * @author Heinrich
 */
public class CodeViewPanel extends JLayeredPane {

    private ChangedCodeFile codeFile;
    private SyntaxHighlighter codeViewPane;
    /**
     * Creates new form CodeViewPanel
     */

    public CodeViewPanel(ChangedCodeFile codeFile) {
        this.codeFile = codeFile;
        initComponents();
        createSyntaxHighlighter();
        createLinePanel();

        linesScrollPane.getVerticalScrollBar().setUnitIncrement(20);
        codeViewPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        codeViewPane.getVerticalScrollBar().setModel(linesScrollPane.getVerticalScrollBar().getModel());
        
        linesScrollPane.getViewport().setOpaque(false);
        this.setLayer(linesScrollPane, JLayeredPane.PALETTE_LAYER);
        this.setLayer(codeViewPane, JLayeredPane.DEFAULT_LAYER);
        linesScrollPane.setSize(200,200);
        //linesScrollPane
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if(codeViewPane.getWidth() == 0 && codeViewPane.getHeight() == 0)
            codeViewPane.setSize(getSize());
        /*if(linesPanel.getWidth() == 0)
            linesPanel.setSize(getWidth(), getLineCount() * 15);*/
    }
    
    private void createLinePanel() {
        int lineCount = getLineCount();
        linesPanel.addLines(lineCount, codeFile);
    }
    
    private void createSyntaxHighlighter() {
        try {
            codeViewPane = CustomComponents.getFileTab(codeFile);
            add(codeViewPane);
        } catch (Exception ex) {
            Logger.getLogger(CodeViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public ChangedCodeFile getCodeFile() {
        return codeFile;
    }

    public void setCodeFile(ChangedCodeFile codeFile) {
        this.codeFile = codeFile;
    }
    
    private int getLineCount() {
        BufferedReader br;
        int lineNums = 0;
        try {
            File file = new File(codeFile.getFilePath());
            br = new BufferedReader(new FileReader(file));
            lineNums = br.lines().toArray().length;
        }
        catch(FileNotFoundException e) {
            e.printStackTrace();
        }
        
        return lineNums;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linesScrollPane = new javax.swing.JScrollPane();
        linesPanel = new com.heinvdende.versionreview.test.client.ui.components.LinesPanel();

        linesScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        linesScrollPane.setOpaque(false);

        javax.swing.GroupLayout linesPanelLayout = new javax.swing.GroupLayout(linesPanel);
        linesPanel.setLayout(linesPanelLayout);
        linesPanelLayout.setHorizontalGroup(
            linesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        linesPanelLayout.setVerticalGroup(
            linesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        linesScrollPane.setViewportView(linesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linesScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );
        setLayer(linesScrollPane, javax.swing.JLayeredPane.PALETTE_LAYER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.heinvdende.versionreview.test.client.ui.components.LinesPanel linesPanel;
    private javax.swing.JScrollPane linesScrollPane;
    // End of variables declaration//GEN-END:variables

}
